MyProject/Controllers/Category_TblController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyProject.Models;

namespace MyProject.Controllers
{
    public class Category_TblController : Controller
    {
        private SportsDbEntities db = new SportsDbEntities();

        // GET: Category_Tbl
        public ActionResult Index()
        {
            return View(db.Category_Tbl.ToList());
        }

        // GET: Category_Tbl/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category_Tbl category_Tbl = db.Category_Tbl.Find(id);
            if (category_Tbl == null)
            {
                return HttpNotFound();
            }
            return View(category_Tbl);
        }

        // GET: Category_Tbl/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Category_Tbl/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Cat_id,Cat_Name")] Category_Tbl category_Tbl)
        {
            if (ModelState.IsValid)
            {
                db.Category_Tbl.Add(category_Tbl);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category_Tbl);
        }

        // GET: Category_Tbl/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category_Tbl category_Tbl = db.Category_Tbl.Find(id);
            if (category_Tbl == null)
            {
                return HttpNotFound();
            }
            return View(category_Tbl);
        }

        // POST: Category_Tbl/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Cat_id,Cat_Name")] Category_Tbl category_Tbl)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category_Tbl).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category_Tbl);
        }

        // GET: Category_Tbl/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category_Tbl category_Tbl = db.Category_Tbl.Find(id);
            if (category_Tbl == null)
            {
                return HttpNotFound();
            }
            return View(category_Tbl);
        }

        // POST: Category_Tbl/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category_Tbl category_Tbl = db.Category_Tbl.Find(id);
            db.Category_Tbl.Remove(category_Tbl);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyProject/Controllers/RequestJoin_TblController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyProject.Models;

namespace MyProject.Controllers
{
    public class RequestJoin_TblController : Controller
    {
        private SportsDbEntities db = new SportsDbEntities();

        // GET: RequestJoin_Tbl
        public ActionResult Index()
        {
            var requestJoin_Tbl = db.RequestJoin_Tbl.Include(r => r.Category_Tbl);
            return View(requestJoin_Tbl.ToList());
        }

        // GET: RequestJoin_Tbl/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RequestJoin_Tbl requestJoin_Tbl = db.RequestJoin_Tbl.Find(id);
            if (requestJoin_Tbl == null)
            {
                return HttpNotFound();
            }
            return View(requestJoin_Tbl);
        }

        // GET: RequestJoin_Tbl/Create
        public ActionResult Create()
        {
            ViewBag.Cat_Fid = new SelectList(db.Category_Tbl, "Cat_id", "Cat_Name");
            return View();
        }

        // POST: RequestJoin_Tbl/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Req_Id,Req_name,Req_Dept,Req_Age,Cat_Fid")] RequestJoin_Tbl requestJoin_Tbl)
        {
            if (ModelState.IsValid)
            {
                db.RequestJoin_Tbl.Add(requestJoin_Tbl);
                db.SaveChanges();
           
                ViewBag.SuccessMessage = "Request successfully sent!";
                return RedirectToAction("Create");
            }

            ViewBag.Cat_Fid = new SelectList(db.Category_Tbl, "Cat_id", "Cat_Name", requestJoin_Tbl.Cat_Fid);
            return View(requestJoin_Tbl);
        }

        

        // GET: RequestJoin_Tbl/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RequestJoin_Tbl requestJoin_Tbl = db.RequestJoin_Tbl.Find(id);
            if (requestJoin_Tbl == null)
            {
                return HttpNotFound();
            }
            return View(requestJoin_Tbl);
        }

        // POST: RequestJoin_Tbl/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            RequestJoin_Tbl requestJoin_Tbl = db.RequestJoin_Tbl.Find(id);
            db.RequestJoin_Tbl.Remove(requestJoin_Tbl);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyProject/Controllers/TeamList_TblController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyProject.Models;

namespace MyProject.Controllers
{
    public class TeamList_TblController : Controller
    {
        private SportsDbEntities db = new SportsDbEntities();

        // GET: TeamList_Tbl
        public ActionResult Index()
        {
            var teamList_Tbl = db.TeamList_Tbl.Include(t => t.Category_Tbl);
            return View(teamList_Tbl.ToList());
        }

        // GET: TeamList_Tbl/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TeamList_Tbl teamList_Tbl = db.TeamList_Tbl.Find(id);
            if (teamList_Tbl == null)
            {
                return HttpNotFound();
            }
            return View(teamList_Tbl);
        }

        // GET: TeamList_Tbl/Create
        public ActionResult Create()
        {
            ViewBag.Cat_Bid = new SelectList(db.Category_Tbl, "Cat_id", "Cat_Name");
            return View();
        }

        // POST: TeamList_Tbl/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "team_id,member_name,member_batch,member_dept,other_info,Cat_Bid")] TeamList_Tbl teamList_Tbl)
        {
            if (ModelState.IsValid)
            {
                db.TeamList_Tbl.Add(teamList_Tbl);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Cat_Bid = new SelectList(db.Category_Tbl, "Cat_id", "Cat_Name", teamList_Tbl.Cat_Bid);
            return View(teamList_Tbl);
        }

        // GET: TeamList_Tbl/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TeamList_Tbl teamList_Tbl = db.TeamList_Tbl.Find(id);
            if (teamList_Tbl == null)
            {
                return HttpNotFound();
            }
            ViewBag.Cat_Bid = new SelectList(db.Category_Tbl, "Cat_id", "Cat_Name", teamList_Tbl.Cat_Bid);
            return View(teamList_Tbl);
        }

        // POST: TeamList_Tbl/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "team_id,member_name,member_batch,member_dept,other_info,Cat_Bid")] TeamList_Tbl teamList_Tbl)
        {
            if (ModelState.IsValid)
            {
                db.Entry(teamList_Tbl).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Cat_Bid = new SelectList(db.Category_Tbl, "Cat_id", "Cat_Name", teamList_Tbl.Cat_Bid);
            return View(teamList_Tbl);
        }

        // GET: TeamList_Tbl/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TeamList_Tbl teamList_Tbl = db.TeamList_Tbl.Find(id);
            if (teamList_Tbl == null)
            {
                return HttpNotFound();
            }
            return View(teamList_Tbl);
        }

        // POST: TeamList_Tbl/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TeamList_Tbl teamList_Tbl = db.TeamList_Tbl.Find(id);
            db.TeamList_Tbl.Remove(teamList_Tbl);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyProject/Views/Shared/_AdminLayoutPage1.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    @*<link href="/Content/assets/img/favicon.png" rel="icon">
    <link href="/Content/assets/img/apple-touch-icon.png" rel="apple-touch-icon">*@

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="/Content/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="/Content/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="/Content/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="/Content/assets/vendor/quill/quill.snow.css" rel="stylesheet">
    <link href="/Content/assets/vendor/quill/quill.bubble.css" rel="stylesheet">
    <link href="/Content/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="/Content/assets/vendor/simple-datatables/style.css" rel="stylesheet">
    <link rel="icon" type="image/png" href="
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAAq1BMVEX////gwLS9dVavUR+uTxvCgGXly8Hy5eDMloGsSAiwVCWrRQCuTRfPnorevbC6akaqQgC7cE7atKa1YDf27OfUp5avUiH48fKzWy/79/h7AAC6i5Dy6uuBABKIGSqCABavdnzu4ePs2NDDg2iLJTOlYWjk0tXIjnafVl+JHS2bTFXawsWXQkyEAB2EABuSNkHQsbXJpanDmp6nZm3dxsmzfoTVsKrLn5rRopDWSq8+AAABrUlEQVR4AXTShYKCQBQF0Ks0MyIp3cg6stb2/3/ZDoKtR+kXxMONyVQQJRkvKKqmCbouEDpT8MiYm1QfUdOa3CeTPvlC0Ih6KWM7l+QLajo2Bq5HtcX99YVGPRcDHzACctuCBAbgh8P1KE4AeW6K+kg0LRlI4shHL0yzvCiBSjLp0LyugLLIs/QU0DRZumwB5c2klKgu0K7SrGlOAXnDsXzdAf7MC4HuPWcNNwZg0xyx7W4P7rDbsuFMjsGu6WUbxjabroyO2yEFgyXrr39075tspVSHPF+2XR/BVhjEGT/ahsD+E/M6ib/Gqtk3BvvNOdoiP9k5KTtg0G75QQFuGvw2TQjuwAO2LUabMWDi8PM/+jkgxGjFGrYGYHX5+sf8cwF8Z8Opy01ECWCvV4Y5cSkA/mCbA078LcsLH1BSOQihECAscpb7OIs3LXpLFYD6Bq5l40NeRkJX0MqqPRXhz20gDHHNtYhAvBDGbAKDimTu4lbo8Fmg2nT2V/fzJwY+7lm0HzVKhQWPdEI8qok+IhKesk3hOM+mhxeUQOPlFxVe+zNNFf/DC9iVGEgEAFigMeUoKWyiAAAAAElFTkSuQmCC">
    <!--//fonts-->
    <!-- Template Main CSS File -->
    <link href="/Content/assets/css/style.css" rel="stylesheet">

</head>
<body>
    <!-- ======= Header ======= -->
    <header id="header" class="header fixed-top d-flex align-items-center">

        <div class="d-flex align-items-center justify-content-between">
            <a href="index.html" class="logo d-flex align-items-center">
                <img src="assets/img/logo.png" alt="">
                <span class="d-none d-lg-block">SPORTS ADMIN</span>
            </a>
            <i class="bi bi-list toggle-sidebar-btn"></i>
        </div><!-- End Logo -->



        <nav class="header-nav ms-auto">
            <ul class="d-flex align-items-center">

                <li class="nav-item d-block d-lg-none">
                    <a class="nav-link nav-icon search-bar-toggle " href="#">
                        <i class="bi bi-search"></i>
                    </a>
                </li><!-- End Search Icon-->



                <li class="nav-item dropdown pe-3">

                    <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">


                        <h5>Admin Panel</h5>
                        <span class="d-none d-md-block dropdown-toggle ps-2">

                        </span>



                    </a><!-- End Profile Iamge Icon -->

                    <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
                        <li class="dropdown-header">


                            <span>Admin of Sports Club</span>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>


                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a class="dropdown-item d-flex align-items-center" href="pages-faq.html">
                                <i class="bi bi-question-circle"></i>
                                <span>Need Help?</span>
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>

                        <li>
                            <a class="dropdown-item d-flex align-items-center" href="@Url.Action("Login","Admin_Tbl")">
                                <i class="bi bi-box-arrow-right"></i>
                                <span>Log Out</span>
                            </a>
                        </li>

                    </ul><!-- End Profile Dropdown Items -->
                </li><!-- End Profile Nav -->

            </ul>
        </nav><!-- End Icons Navigation -->

    </header><!-- End Header -->
    <!-- ======= Sidebar ======= -->
    <aside id="sidebar" class="sidebar">

        <ul class="sidebar-nav" id="sidebar-nav">

            <li class="nav-item">
                <a class="nav-link collapsed" href="@Url.Action("Admin","Home")">
                    <i class="bi bi-grid"></i>
                    <span>Dashboard</span>
                </a>
            </li><!-- End Dashboard Nav -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="@Url.Action("Index","User_Tbl")">
                    <i class="bi bi-file-earmark"></i>
                    <span> Member Accounts</span>
                </a>
            </li><!-- End Blank Page Nav -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="@Url.Action("Index","RequestJoin_Tbl")">
                    <i class="bi bi-file-earmark"></i>
                    <span> RequestToJoin </span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" href="@Url.Action("Index","TeamList_Tbl")">
                    <i class="bi bi-file-earmark"></i>
                    <span>Team Members List</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link collapsed" href=" ">
                    <i class="bi bi-file-earmark"></i>
                    <span>News &Aacute; Events</span>
                </a>
            </li>

            <li class="nav-item">

            </li><!-- End Forms Nav -->
            <a class="nav-link collapsed" href="@Url.Action("")">
                <i class="bi bi-file-earmark"></i>
                <span>Gallery </span>
            </a>

            <li class="nav-item">
                <a class="nav-link collapsed" href="@Url.Action("Index","Home")">
                    <i class="bi bi-file-earmark"></i>
                    <span>Offcial site</span>
                </a>
            </li><!-- End Blank Page Nav -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="@Url.Action("Create","Category_Tbl")">
                    <i class="bi bi-file-earmark"></i>
                    <span>Add New Sport</span>
                </a>
                
            </li><!-- End Blank Page Nav -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="@Url.Action("Index","Admin_Tbl")">
                    <i class="bi bi-file-earmark"></i>
                    <span>Admin Details</span>
                </a>
        </ul>

    </aside><!-- End Sidebar-->
    <main id="main" class="main">


        @RenderBody()
    </main>

    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer">
        <div class="copyright">
            &copy; Copyright <strong><span>SPORT CLUB | MACFAST</span></strong>. All Rights Reserved
        </div>
        <div class="credits">

            Designed by <a href="#">Sandeep S Kumar | 2023</a>
        </div>
    </footer><!-- End Footer -->

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="/Content/assets/vendor/apexcharts/apexcharts.min.js"></script>
    <script src="/Content/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="/Content/assets/vendor/chart.js/chart.umd.js"></script>
    <script src="/Content/assets/vendor/echarts/echarts.min.js"></script>
    <script src="/Content/assets/vendor/quill/quill.min.js"></script>
    <script src="/Content/assets/vendor/simple-datatables/simple-datatables.js"></script>
    <script src="/Content/assets/vendor/tinymce/tinymce.min.js"></script>
    <script src="/Content/assets/vendor/php-email-form/validate.js"></script>

    <!-- Template Main JS File -->
    <script src="/Content/admin/assets/js/main.js"></script>
</body>
</html>

MyProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<title>SPORTS - MACFAST | 2023</title>
	<!--fonts-->
		<link href='http://fonts.googleapis.com/css?family=Francois+One' rel='stylesheet' type='text/css'>
		<link href='http://fonts.googleapis.com/css?family=Cabin:400,500,600,700' rel='stylesheet' type='text/css'>	
	   <link href='http://fonts.googleapis.com/css?family=Audiowide' rel='stylesheet' type='text/css'>
       <link rel="icon" type="image/png" href="
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAMAAABEpIrGAAAAq1BMVEX////gwLS9dVavUR+uTxvCgGXly8Hy5eDMloGsSAiwVCWrRQCuTRfPnorevbC6akaqQgC7cE7atKa1YDf27OfUp5avUiH48fKzWy/79/h7AAC6i5Dy6uuBABKIGSqCABavdnzu4ePs2NDDg2iLJTOlYWjk0tXIjnafVl+JHS2bTFXawsWXQkyEAB2EABuSNkHQsbXJpanDmp6nZm3dxsmzfoTVsKrLn5rRopDWSq8+AAABrUlEQVR4AXTShYKCQBQF0Ks0MyIp3cg6stb2/3/ZDoKtR+kXxMONyVQQJRkvKKqmCbouEDpT8MiYm1QfUdOa3CeTPvlC0Ih6KWM7l+QLajo2Bq5HtcX99YVGPRcDHzACctuCBAbgh8P1KE4AeW6K+kg0LRlI4shHL0yzvCiBSjLp0LyugLLIs/QU0DRZumwB5c2klKgu0K7SrGlOAXnDsXzdAf7MC4HuPWcNNwZg0xyx7W4P7rDbsuFMjsGu6WUbxjabroyO2yEFgyXrr39075tspVSHPF+2XR/BVhjEGT/ahsD+E/M6ib/Gqtk3BvvNOdoiP9k5KTtg0G75QQFuGvw2TQjuwAO2LUabMWDi8PM/+jkgxGjFGrYGYHX5+sf8cwF8Z8Opy01ECWCvV4Y5cSkA/mCbA078LcsLH1BSOQihECAscpb7OIs3LXpLFYD6Bq5l40NeRkJX0MqqPRXhz20gDHHNtYhAvBDGbAKDimTu4lbo8Fmg2nT2V/fzJwY+7lm0HzVKhQWPdEI8qok+IhKesk3hOM+mhxeUQOPlFxVe+zNNFf/DC9iVGEgEAFigMeUoKWyiAAAAAElFTkSuQmCC">
	<!--//fonts-->		
		<link href="~/Content/css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
		<link href="~/Content/css/style.css" rel="stylesheet" type="text/css" media="all" />
	<!-- for-mobile-apps -->
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="keywords" content="soccer Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template, 
		Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
		<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>

		<script src="~/Content/js/jquery.min.js"></script>
	
</head>
<body>

<div class="header">
	 <div class="container">
		 <div class="logo">
			   <h1><a href=@Url.Action("Index","Home")>MAC SPORTS</a></h1>
		 </div>	
		 <div class="top-menu">
			 <span class="menu"></span>
             <ul>

                 <li class="nav-item active">@Html.ActionLink("HOME", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                 <li class="nav-item">@Html.ActionLink("ABOUT US", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>

                 @if (Session["IsLoggedIn"] == null )

				 {
                     <li class="nav-item">@Html.ActionLink("LOGIN", "login", "User_Tbl", new { area = "" }, new { @class = "nav-link" })</li>
				 }
                     @if (Session["IsLoggedIn"] != null && (bool)Session["IsLoggedIn"])

                     {
                         <li class="nav-item">@Html.ActionLink("TO JOIN", "Create", "RequestJoin_Tbl", new { area = "" }, new { @class = "nav-link" })</li>
                         <li class="nav-item">@Html.ActionLink("GALLERY ", "", "", new { area = "" }, new { @class = "nav-link" })</li>
                         <li class="nav-item">@Html.ActionLink("NEWS & EVENTS", "", "", new { area = "" }, new { @class = "nav-link" })</li>
                         <li class="nav-item">@Html.ActionLink("LOGOUT", "Logout", "User_Tbl", new { area = "" }, new { @class = "nav-link" })</li>
                     }
                 </ul>			 
		 </div>			
	
		 <script>
				$("span.menu").click(function(){
					$(".top-menu ul").slideToggle("slow" , function(){
					});
				});
		 </script>
	  	

		 <div class="clearfix"></div>
	 </div>
</div>

<div class="strip">
	 <div class="container">
	 <div class="search">
		    <form>
		    	<input type="text" value="" placeholder="Search...">
				<input type="submit" value="">
			</form>
     </div>     
	 <div class="social">			 
			 <a href="#"><i class="facebook"></i></a>
			 <a href="#"><i class="twitter"></i></a>
			 <a href="#"><i class="dribble"></i></a>	
			 <a href="#"><i class="google"></i></a>	
			 <a href="#"><i class="youtube"></i></a>	
	 </div>
		<div class="clearfix"></div>
		</div>
</div>
<!-- banner -->
<div class="banner">
		<script src="js/responsiveslides.min.js"></script>
  <script>
    $(function () {
      $("#slider").responsiveSlides({
      	auto: true,
      	speed: 300,
        manualControls: '#slider3-pager',
      });
    });
  </script>
	</div>

 @RenderBody()
<!--footer-->
<div class="footer">
	 <div class="container">
		 <div class="copywrite">
			 <p>© 2023 All Rights Reseverd Design by <a href="">MAC - TEAM</a> </p>
		 </div>
         <div class="footer-menu">
             <ul>

                 <li class="nav-item active">@Html.ActionLink("HOME", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                 <li class="nav-item">@Html.ActionLink("ABOUT US", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>

                 @if (Session["IsLoggedIn"] == null)

                 {
                     <li class="nav-item">@Html.ActionLink("LOGIN", "login", "User_Tbl", new { area = "" }, new { @class = "nav-link" })</li>
                 }
                 @if (Session["IsLoggedIn"] != null && (bool)Session["IsLoggedIn"])

                 {
                     <li class="nav-item">@Html.ActionLink("TO JOIN", "Create", "RequestJoin_Tbl", new { area = "" }, new { @class = "nav-link" })</li>
                     <li class="nav-item">@Html.ActionLink("GALLERY ", "", "", new { area = "" }, new { @class = "nav-link" })</li>
                     <li class="nav-item">@Html.ActionLink("NEWS & EVENTS", "", "", new { area = "" }, new { @class = "nav-link" })</li>
                     <li class="nav-item">@Html.ActionLink("LOGOUT", "Logout", "User_Tbl", new { area = "" }, new { @class = "nav-link" })</li>
                 }
                 <li class="nav-item">@Html.ActionLink("ADMIN", "Login", "Admin_Tbl", new { area = "" }, new { @class = "nav-link" })</li>
             </ul>
         </div>
		 <div class="clearfix"></div>
	 </div>
</div>
<!-- //footer -->
</body>
</html>